create table agency
(
	agency_id        bigint generated by default as identity,
	name             varchar(255) not null,
	logo_image_url   text         not null,
	nation           varchar(100) not null default 'KOREA',
	established_date date,
	created_at       timestamp(6) not null,
	last_modified_at timestamp(6) not null,
	constraint PK_agency primary key (agency_id)
);

create table artist
(
	artist_id         bigint generated by default as identity,
	agency_id         bigint,
	name              varchar(255) not null,
	profile_image_url text         not null,
	debut_date        date,
	created_at        timestamp(6) not null,
	last_modified_at  timestamp(6) not null,
	constraint PK_artist primary key (artist_id)
);

create table member
(
	member_id         bigint generated by default as identity,
	role              varchar(30)  not null default 'NORMAL',
	nickname          varchar(100) not null,
	sns_type          varchar(20)  not null,
	sns_id            varchar(255) not null,
	profile_image_url text         not null,
	status            varchar(20)  not null,
	last_login_at     timestamp(6) not null,
	created_at        timestamp(6) not null,
	last_modified_at  timestamp(6) not null,
	constraint PK_member primary key (member_id)
);

create table channel
(
	channel_id       bigint generated by default as identity,
	agency_id        bigint,
	artist_id        bigint,
	type             varchar(100) not null,
	url              varchar(255) not null,
	created_at       timestamp(6) not null,
	last_modified_at timestamp(6) not null,
	constraint pk_channel primary key (channel_id)
);

alter table public.artist
	add constraint FK_artist_TO_agency
		foreign key (agency_id) references public.agency;

alter table public.channel
	add constraint fk_channel_to_agency
		foreign key (agency_id) references public.agency;

alter table public.channel
	add constraint fk_channel_to_artist
		foreign key (artist_id) references public.artist;
