create table post
(
	post_id          bigint generated by default as identity,
	member_id        bigint       not null,
	title            varchar(100) not null,
	content text         not null,
	created_at       timestamp(6) not null,
	last_modified_at timestamp(6) not null,
	constraint pk_post primary key (post_id)
);

alter table public.post
	add constraint fk_post_to_member
		foreign key (member_id) references public.member;