create table post_media
(
	post_media_id      bigint generated by default as identity,
	post_id            bigint       not null,
	media_type         varchar(20)  not null,
	content_type       varchar(100) not null,
	original_file_name text         not null,
	original_url       text         not null,
	thumbnail_url      text         not null,
	display_order      bigint          not null,
	created_at         timestamp(6) not null,
	last_modified_at   timestamp(6) not null,
	constraint pk_post_media primary key (post_media_id)
);

alter table public.post_media
	add constraint fk_post_media_to_post
		foreign key (post_id) references public.post;