create table business_profile
(
	business_profile_id bigint generated by default as identity,
	member_id           bigint not null,
	agency_id			bigint,
	artist_id			bigint,
	type                varchar(100) not null,
	created_at          timestamp(6) not null,
	last_modified_at    timestamp(6) not null,
	constraint pk_business_profile primary key (business_profile_id)
);

alter table public.business_profile
	add constraint fk_business_profile_to_member
		foreign key (member_id) references public.member;

alter table public.business_profile
	add constraint fk_business_profile_to_agency
		foreign key (agency_id) references public.agency;

alter table public.business_profile
	add constraint fk_business_profile_to_artist
		foreign key (artist_id) references public.artist;