spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(VhGRQHkSrPWgK7xI0ZJrIZ58Wj7qWqw3W9F45P15j7Moj4mKDwKSBZdwA1yomlSqICINUWYhzBBBazeWsUKkAOn6TklQ4iu/zKlW1xM0KvcnLDG7E6Q65MtemPNJ3URP)
    username: ENC(mBKCab+egt/g9y9x3k//Jg==)
    password: ENC(TZiXc8IRxQh8TZoNs0W1tUP6WK1uVUUd)
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration/dev
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  jackson:
    deserialization:
      fail-on-null-for-primitives: true

management:
  endpoints:
    web:
      exposure:
        include: env

# 카카오 OAuth 설정
kakao:
  client-id: 70b5d2ebdeab88e65b4caa45fa39df78
  redirect-uri: http://localhost:3000/api/auth/kakao/callback

# JWT 설정
jwt:
  secret-key: "isekaiSecretKey12345678901234567890123456789012" # 최소 32바이트 이상의 비밀 키 (실제 운영 환경에서는 환경 변수로 관리해야 함)
  access-token-expiration-ms: 1800000 # 30분 (밀리초 단위)
  refresh-token-expiration-ms: 604800000 # 7일 (밀리초 단위)
  issuer: "isekai-api"
  
decorator:
  datasource:
    p6spy:
      enable-logging: false