create table agency
(
	agency_id        bigint generated by default as identity,
	name             varchar(255),
	logo_image_url   text,
	nation           varchar(255),
	established_date date,
	closed_date      date,
	created_at       timestamp(6),
	last_modified_at timestamp(6),
	constraint PK_agency primary key (agency_id)
);

create table v_tuber
(
	v_tuber_id        bigint generated by default as identity,
	agency_id         bigint,
	name              varchar(255),
	profile_image_url text,
	age               integer not null,
	height            integer not null,
	generation        varchar(255),
	platform          varchar(255),
	race              varchar(255),
	created_at        timestamp(6),
	last_modified_at  timestamp(6),
	constraint PK_v_tuber primary key (v_tuber_id)
);

create table fandom
(
	fandom_id        bigint generated by default as identity,
	agency_id        bigint,
	v_tuber_id       bigint,
	name             varchar(255),
	logo_image_url   text,
	created_at       timestamp(6),
	last_modified_at timestamp(6),
	constraint PK_fandom primary key (fandom_id)
);

create table member
(
	member_id        bigint generated by default as identity,
	role             varchar(255),
	created_at       timestamp(6),
	last_modified_at timestamp(6),
	constraint PK_member primary key (member_id)
);

alter table public.fandom
	add constraint FK_fandom_TO_agency
		foreign key (agency_id) references public.agency;

alter table public.fandom
	add constraint FK_fandom_TO_v_tuber
		foreign key (v_tuber_id) references public.v_tuber;

alter table public.v_tuber
	add constraint FK_v_tuber_TO_agency
		foreign key (agency_id) references public.agency;